name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Установка Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Установка зависимостей
        run: poetry install --no-interaction --with dev
        
      - name: Проверка типов с mypy
        run: poetry run mypy . --explicit-package-bases

      - name: Проверка форматирования с black
        run: poetry run black --check .
        
      - name: Проверка импортов с isort
        run: poetry run isort --check-only --profile black .
